# Generated by Django 5.2.6 on 2025-09-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('gerada_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('siape', models.CharField(max_length=20)),
                ('registro_conselho', models.CharField(blank=True, max_length=20)),
                ('classe', models.CharField(blank=True, max_length=10)),
                ('cargo', models.CharField(max_length=50)),
                ('vinculo', models.CharField(max_length=50)),
                ('ch_semanal', models.IntegerField()),
                ('grupo', models.CharField(blank=True, max_length=50)),
                ('preferencias_turno', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_fim', models.TimeField(null=True)),
                ('duracao_horas', models.FloatField()),
                ('periodo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('portaria', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='AtribuicaoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escala')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
                ('tipo_turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoturno')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade'),
        ),
        migrations.AddField(
            model_name='escala',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade'),
        ),
    ]
