# Generated by Django 5.2.6 on 2025-09-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicaoescala',
            name='ch_mensal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atribuicaoescala',
            name='dia',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='atribuicaoescala',
            name='tipo_turno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.tipoturno'),
            preserve_default=False,
        ),
    ]
