# Generated by Django 5.2.6 on 2025-09-20 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atribuicaoescala_ch_mensal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_fim', models.TimeField(null=True)),
                ('horas', models.FloatField()),
                ('periodo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='atribuicaoescala',
            name='tipo_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turno'),
        ),
        migrations.DeleteModel(
            name='TipoTurno',
        ),
    ]
