# Generated by Django 5.2.6 on 2025-09-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atribuicaoescala',
            name='escala',
        ),
        migrations.RemoveField(
            model_name='atribuicaoescala',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='atribuicaoescala',
            name='tipo_turno',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='unidade',
        ),
        migrations.DeleteModel(
            name='Feriado',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='unidade',
        ),
        migrations.DeleteModel(
            name='AtribuicaoEscala',
        ),
        migrations.DeleteModel(
            name='TipoTurno',
        ),
        migrations.DeleteModel(
            name='Escala',
        ),
        migrations.DeleteModel(
            name='Ferias',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
